runner:
  rwlint:
    cmd: docker-compose exec -T app /bin/bash -c "yarn rw lint"
    errorformat:
      - '%-P%f'
      - '%#%l:%c %# %trror  %m'
      - '%#%l:%c %# %tarning  %m'
      - '%-Q'
      - '%-G%.%#'
  rwtest:
    cmd: docker-compose exec -T app /bin/bash -c "yarn rw test --no-watch"
    errorformat:
      - '%-G%[%^ ]%.%#'
      - '%E%.%#● %m'
      - '%Z%.%#at %.%# (%f:%l:%c)'
      - '%C%.%#'
      - '%-G%.%#'
