runner:
  rwlint:
    cmd: docker-compose exec -T app /bin/bash -c "yarn rw lint"
    format: rdjson
    level: warning
  rwtest:
    cmd: docker-compose exec -T app /bin/bash -c "yarn rw test --no-watch"
    errorformat:
      - '%-G%[%^ ]%.%#'
      - '%E%.%#● %m'
      - '%Z%.%#at %.%# (%f:%l:%c)'
      - '%C%.%#'
      - '%-G%.%#'
    level: warning
