version: "3.8"
services:
  app:
    command: /bin/bash -c "while true; do sleep 1000; done"
    build: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - RWJS_DEV_API_URL=${RWJS_DEV_API_URL:-http://localhost}
      - SESSION_SECRET=${SESSION_SECRET:-dummy}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?connection_limit=1
      - TEST_DATABASE_URL=postgres://postgres:postgres@db-test:5432/postgres_test?connection_limit=1
      - AUTH0_DOMAIN=${AUTH0_DOMAIN:-dev-za04s8oi.us.auth0.com}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID:-pnSIWCZXS62fyguWBRjxEhS0OIPJHB08}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI:-http://localhost:8910}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE:-https://ateaparty-manager-dev.api}
    ports:
      - "7910:7910" # storybook
      - "8910:8910" # redwoodjs web
      - "8911:8911"
      - "18911:18911"
      - "5555:5555"
    depends_on:
      - db
      - db-test
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./dev.db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-test:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_test
    volumes:
      - ./dev.db/data-test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
