version: "3.8"
services:
  app:
    command: /bin/bash -c "while true; do sleep 1000; done"
    build: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - RWJS_DEV_API_URL=${RWJS_DEV_API_URL:-http://localhost}
      - SESSION_SECRET=${SESSION_SECRET:-dummy}
      - DATABASE_URL=mysql://root:password@db:3306/database?connection_limit=1
      - TEST_DATABASE_URL=mysql://root:password@db-test:3306/db-test?connection_limit=1
      - AUTH0_DOMAIN=${AUTH0_DOMAIN:-dev-za04s8oi.us.auth0.com}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID:-pnSIWCZXS62fyguWBRjxEhS0OIPJHB08}
      - AUTH0_REDIRECT_URI=${AUTH0_REDIRECT_URI:-http://localhost:8910}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE:-https://ateaparty-manager-dev.api}
      - DISCORD_GUILD_ID=${DEV_DISCORD_GUILD_ID:-dummy}
      - DISCORD_BOT_TOKEN=${DEV_DISCORD_BOT_TOKEN:-dummy}
    ports:
      - "7910:7910" # storybook
      - "8910:8910" # redwoodjs web
      - "8911:8911"
      - "18911:18911"
      - "5555:5555"
    depends_on:
      - db
      - db-test
  db:
    image: mysql:8
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - ./dev.db/data:/var/lib/mysql
    ports:
      - "3306:3306"
  db-test:
    image: mysql:8
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db-test
    volumes:
      - ./dev.db/data-test:/var/lib/mysql
    ports:
      - "3307:3306"
