name: "Issue Links"
on:
  pull_request:
    types: [opened]

jobs:
  issue-link:
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-prefix: ""
          resolve: "false"
          link-style: "comment"
