name: reviewdog
on:
  pull_request:
permissions:
  pull-requests: write

jobs:
  reviewdog:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest  # use the latest reviewdog

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint --output-file ./eslint-report.json --format json

      - name: ESLint with reviewdog
        run: reviewdog -reporter=github-pr-review -f=eslint -name="ESLint" -diff="git diff FETCH_HEAD"
